name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Test this action
        uses: ./
