name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Test this action
        uses: ./
